version: "3"
services:
  mysql-docker:
    container_name: mysql-57
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "veus_test"
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/data:/var/lib/mysql:rw"
    networks:
      - developer
networks:
  developer:
    driver: bridge
